image: Visual Studio 2017
platform: Any CPU

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: 'My Project\AssemblyInfo.vb'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(GIT_HASH)-$(CONFIG_LOWER)'

init:
  - git config --global core.autocrlf input
  - ps: $env:CONFIG_LOWER = $env:CONFIGURATION.ToLower()
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)

before_build:
  - nuget restore

build:
  project: ALTTPRCropDashboard.sln
  verbosity: minimal
  
cache:
  - packages -> **\packages.config 

artifacts:
  - path: bin\$(configuration)
    name: alttprcropdashboard-$(configuration)
