'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TimerName_Runner1() As String
            Get
                Return CType(Me("TimerName_Runner1"),String)
            End Get
            Set
                Me("TimerName_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GameName_Runner1() As String
            Get
                Return CType(Me("GameName_Runner1"),String)
            End Get
            Set
                Me("GameName_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("22")>  _
        Public Property DefaultCropTop() As Integer
            Get
                Return CType(Me("DefaultCropTop"),Integer)
            End Get
            Set
                Me("DefaultCropTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("53")>  _
        Public Property DefaultCropBottom() As Integer
            Get
                Return CType(Me("DefaultCropBottom"),Integer)
            End Get
            Set
                Me("DefaultCropBottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GameName_Runner2() As String
            Get
                Return CType(Me("GameName_Runner2"),String)
            End Get
            Set
                Me("GameName_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TimerName_Runner2() As String
            Get
                Return CType(Me("TimerName_Runner2"),String)
            End Get
            Set
                Me("TimerName_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ws://127.0.0.1")>  _
        Public Property ConnectionString1() As String
            Get
                Return CType(Me("ConnectionString1"),String)
            End Get
            Set
                Me("ConnectionString1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ws://127.0.0.1")>  _
        Public Property ConnectionString2() As String
            Get
                Return CType(Me("ConnectionString2"),String)
            End Get
            Set
                Me("ConnectionString2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password1() As String
            Get
                Return CType(Me("Password1"),String)
            End Get
            Set
                Me("Password1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password2() As String
            Get
                Return CType(Me("Password2"),String)
            End Get
            Set
                Me("Password2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunnerOBS_Runner1() As String
            Get
                Return CType(Me("RunnerOBS_Runner1"),String)
            End Get
            Set
                Me("RunnerOBS_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrackerOBS_Runner1() As String
            Get
                Return CType(Me("TrackerOBS_Runner1"),String)
            End Get
            Set
                Me("TrackerOBS_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunnerOBS_Runner2() As String
            Get
                Return CType(Me("RunnerOBS_Runner2"),String)
            End Get
            Set
                Me("RunnerOBS_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property TrackerOBS_Runner2() As String
            Get
                Return CType(Me("TrackerOBS_Runner2"),String)
            End Get
            Set
                Me("TrackerOBS_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CommentaryOBS() As String
            Get
                Return CType(Me("CommentaryOBS"),String)
            End Get
            Set
                Me("CommentaryOBS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property VLCMenuBar() As Boolean
            Get
                Return CType(Me("VLCMenuBar"),Boolean)
            End Get
            Set
                Me("VLCMenuBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property VLCPlayPauseControls() As Boolean
            Get
                Return CType(Me("VLCPlayPauseControls"),Boolean)
            End Get
            Set
                Me("VLCPlayPauseControls") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VLCStatusBar() As Boolean
            Get
                Return CType(Me("VLCStatusBar"),Boolean)
            End Get
            Set
                Me("VLCStatusBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VLCOverrideDefault() As Boolean
            Get
                Return CType(Me("VLCOverrideDefault"),Boolean)
            End Get
            Set
                Me("VLCOverrideDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HasFinishedWelcome() As Boolean
            Get
                Return CType(Me("HasFinishedWelcome"),Boolean)
            End Get
            Set
                Me("HasFinishedWelcome") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TwitchChannel() As String
            Get
                Return CType(Me("TwitchChannel"),String)
            End Get
            Set
                Me("TwitchChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DefaultConnection() As Boolean
            Get
                Return CType(Me("DefaultConnection"),Boolean)
            End Get
            Set
                Me("DefaultConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4444")>  _
        Public Property ConnectionPort1() As Integer
            Get
                Return CType(Me("ConnectionPort1"),Integer)
            End Get
            Set
                Me("ConnectionPort1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4443")>  _
        Public Property ConnectionPort2() As Integer
            Get
                Return CType(Me("ConnectionPort2"),Integer)
            End Get
            Set
                Me("ConnectionPort2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpgradeRequired() As Boolean
            Get
                Return CType(Me("UpgradeRequired"),Boolean)
            End Get
            Set
                Me("UpgradeRequired") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExpertMode() As Boolean
            Get
                Return CType(Me("ExpertMode"),Boolean)
            End Get
            Set
                Me("ExpertMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlwaysOnTop() As Boolean
            Get
                Return CType(Me("AlwaysOnTop"),Boolean)
            End Get
            Set
                Me("AlwaysOnTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("%LOCALAPPDATA%\Streamlink\bin\streamlink.exe")>  _
        Public Property StreamlinkPath() As String
            Get
                Return CType(Me("StreamlinkPath"),String)
            End Get
            Set
                Me("StreamlinkPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftStreamlinkVlcParams() As String
            Get
                Return CType(Me("LeftStreamlinkVlcParams"),String)
            End Get
            Set
                Me("LeftStreamlinkVlcParams") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightStreamlinkVlcParams() As String
            Get
                Return CType(Me("RightStreamlinkVlcParams"),String)
            End Get
            Set
                Me("RightStreamlinkVlcParams") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GameSettings() As String
            Get
                Return CType(Me("GameSettings"),String)
            End Get
            Set
                Me("GameSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("633")>  _
        Public Property DefaultHeight() As Integer
            Get
                Return CType(Me("DefaultHeight"),Integer)
            End Get
            Set
                Me("DefaultHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("863")>  _
        Public Property DefaultWidth() As Integer
            Get
                Return CType(Me("DefaultWidth"),Integer)
            End Get
            Set
                Me("DefaultWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("633")>  _
        Public Property FourRacerHeight() As Integer
            Get
                Return CType(Me("FourRacerHeight"),Integer)
            End Get
            Set
                Me("FourRacerHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1523")>  _
        Public Property FourRacerWidth() As Integer
            Get
                Return CType(Me("FourRacerWidth"),Integer)
            End Get
            Set
                Me("FourRacerWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("112")>  _
        Public Property DefaultGBHeight() As Integer
            Get
                Return CType(Me("DefaultGBHeight"),Integer)
            End Get
            Set
                Me("DefaultGBHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("658")>  _
        Public Property DefaultGBWidth() As Integer
            Get
                Return CType(Me("DefaultGBWidth"),Integer)
            End Get
            Set
                Me("DefaultGBWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("112")>  _
        Public Property FourRacerGBHeight() As Integer
            Get
                Return CType(Me("FourRacerGBHeight"),Integer)
            End Get
            Set
                Me("FourRacerGBHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1327")>  _
        Public Property FourRacerGBWidth() As Integer
            Get
                Return CType(Me("FourRacerGBWidth"),Integer)
            End Get
            Set
                Me("FourRacerGBWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FourPlayers() As Boolean
            Get
                Return CType(Me("FourPlayers"),Boolean)
            End Get
            Set
                Me("FourPlayers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TimerName_Runner3() As String
            Get
                Return CType(Me("TimerName_Runner3"),String)
            End Get
            Set
                Me("TimerName_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GameName_Runner3() As String
            Get
                Return CType(Me("GameName_Runner3"),String)
            End Get
            Set
                Me("GameName_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GameName_Runner4() As String
            Get
                Return CType(Me("GameName_Runner4"),String)
            End Get
            Set
                Me("GameName_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TimerName_Runner4() As String
            Get
                Return CType(Me("TimerName_Runner4"),String)
            End Get
            Set
                Me("TimerName_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunnerOBS_Runner3() As String
            Get
                Return CType(Me("RunnerOBS_Runner3"),String)
            End Get
            Set
                Me("RunnerOBS_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunnerOBS_Runner4() As String
            Get
                Return CType(Me("RunnerOBS_Runner4"),String)
            End Get
            Set
                Me("RunnerOBS_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrackerOBS_Runner3() As String
            Get
                Return CType(Me("TrackerOBS_Runner3"),String)
            End Get
            Set
                Me("TrackerOBS_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrackerOBS_Runner4() As String
            Get
                Return CType(Me("TrackerOBS_Runner4"),String)
            End Get
            Set
                Me("TrackerOBS_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("558")>  _
        Public Property BoundingSizeWidthGameTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthGameTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthGameTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("446")>  _
        Public Property BoundingSizeHeightGameTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightGameTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightGameTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("178")>  _
        Public Property BoundingSizeWidthTimerTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthTimerTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthTimerTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("47")>  _
        Public Property BoundingSizeHeightTimerTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightTimerTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightTimerTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("383")>  _
        Public Property BoundingSizeWidthGameFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthGameFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthGameFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property BoundingSizeHeightGameFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightGameFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightGameFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("119")>  _
        Public Property BoundingSizeWidthTimerFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthTimerFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthTimerFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property BoundingSizeHeightTimerFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightTimerFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightTimerFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1116")>  _
        Public Property PositionXTimerFourPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionXTimerFourPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionXTimerFourPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("51")>  _
        Public Property PositionYTimerFourPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionYTimerFourPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionYTimerFourPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1116")>  _
        Public Property PositionXTimerFourPlayer_Runner4() As Integer
            Get
                Return CType(Me("PositionXTimerFourPlayer_Runner4"),Integer)
            End Get
            Set
                Me("PositionXTimerFourPlayer_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("410")>  _
        Public Property PositionYTimerFourPlayer_Runner4() As Integer
            Get
                Return CType(Me("PositionYTimerFourPlayer_Runner4"),Integer)
            End Get
            Set
                Me("PositionYTimerFourPlayer_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property PositionXTimerFourPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionXTimerFourPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionXTimerFourPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("52")>  _
        Public Property PositionYTimerFourPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionYTimerFourPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionYTimerFourPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property PositionXTimerFourPlayer_Runner3() As Integer
            Get
                Return CType(Me("PositionXTimerFourPlayer_Runner3"),Integer)
            End Get
            Set
                Me("PositionXTimerFourPlayer_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("410")>  _
        Public Property PositionYTimerFourPlayer_Runner3() As Integer
            Get
                Return CType(Me("PositionYTimerFourPlayer_Runner3"),Integer)
            End Get
            Set
                Me("PositionYTimerFourPlayer_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("676")>  _
        Public Property PositionXGameFourPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionXGameFourPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionXGameFourPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property PositionYGameFourPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionYGameFourPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionYGameFourPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("676")>  _
        Public Property PositionXGameFourPlayer_Runner4() As Integer
            Get
                Return CType(Me("PositionXGameFourPlayer_Runner4"),Integer)
            End Get
            Set
                Me("PositionXGameFourPlayer_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("368")>  _
        Public Property PositionYGameFourPlayer_Runner4() As Integer
            Get
                Return CType(Me("PositionYGameFourPlayer_Runner4"),Integer)
            End Get
            Set
                Me("PositionYGameFourPlayer_Runner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("220")>  _
        Public Property PositionXGameFourPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionXGameFourPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionXGameFourPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property PositionYGameFourPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionYGameFourPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionYGameFourPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("220")>  _
        Public Property PositionXGameFourPlayer_Runner3() As Integer
            Get
                Return CType(Me("PositionXGameFourPlayer_Runner3"),Integer)
            End Get
            Set
                Me("PositionXGameFourPlayer_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("368")>  _
        Public Property PositionYGameFourPlayer_Runner3() As Integer
            Get
                Return CType(Me("PositionYGameFourPlayer_Runner3"),Integer)
            End Get
            Set
                Me("PositionYGameFourPlayer_Runner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1046")>  _
        Public Property PositionXTimerTwoPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionXTimerTwoPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionXTimerTwoPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property PositionYTimerTwoPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionYTimerTwoPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionYTimerTwoPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("56")>  _
        Public Property PositionXTimerTwoPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionXTimerTwoPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionXTimerTwoPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property PositionYTimerTwoPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionYTimerTwoPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionYTimerTwoPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("674")>  _
        Public Property PositionXGameTwoPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionXGameTwoPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionXGameTwoPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("83")>  _
        Public Property PositionYGameTwoPlayer_Runner2() As Integer
            Get
                Return CType(Me("PositionYGameTwoPlayer_Runner2"),Integer)
            End Get
            Set
                Me("PositionYGameTwoPlayer_Runner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("48")>  _
        Public Property PositionXGameTwoPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionXGameTwoPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionXGameTwoPlayer_Runner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("83")>  _
        Public Property PositionYGameTwoPlayer_Runner1() As Integer
            Get
                Return CType(Me("PositionYGameTwoPlayer_Runner1"),Integer)
            End Get
            Set
                Me("PositionYGameTwoPlayer_Runner1") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ALTTPRCropDashboard.My.MySettings
            Get
                Return Global.ALTTPRCropDashboard.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
