'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftTimerName() As String
            Get
                Return CType(Me("LeftTimerName"),String)
            End Get
            Set
                Me("LeftTimerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftGameName() As String
            Get
                Return CType(Me("LeftGameName"),String)
            End Get
            Set
                Me("LeftGameName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("22")>  _
        Public Property DefaultCropTop() As Integer
            Get
                Return CType(Me("DefaultCropTop"),Integer)
            End Get
            Set
                Me("DefaultCropTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("53")>  _
        Public Property DefaultCropBottom() As Integer
            Get
                Return CType(Me("DefaultCropBottom"),Integer)
            End Get
            Set
                Me("DefaultCropBottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightGameName() As String
            Get
                Return CType(Me("RightGameName"),String)
            End Get
            Set
                Me("RightGameName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightTimerName() As String
            Get
                Return CType(Me("RightTimerName"),String)
            End Get
            Set
                Me("RightTimerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ws://127.0.0.1")>  _
        Public Property ConnectionString1() As String
            Get
                Return CType(Me("ConnectionString1"),String)
            End Get
            Set
                Me("ConnectionString1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ws://127.0.0.1")>  _
        Public Property ConnectionString2() As String
            Get
                Return CType(Me("ConnectionString2"),String)
            End Get
            Set
                Me("ConnectionString2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password1() As String
            Get
                Return CType(Me("Password1"),String)
            End Get
            Set
                Me("Password1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password2() As String
            Get
                Return CType(Me("Password2"),String)
            End Get
            Set
                Me("Password2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftRunnerOBS() As String
            Get
                Return CType(Me("LeftRunnerOBS"),String)
            End Get
            Set
                Me("LeftRunnerOBS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftTrackerOBS() As String
            Get
                Return CType(Me("LeftTrackerOBS"),String)
            End Get
            Set
                Me("LeftTrackerOBS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightRunnerOBS() As String
            Get
                Return CType(Me("RightRunnerOBS"),String)
            End Get
            Set
                Me("RightRunnerOBS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RightTrackerOBS() As String
            Get
                Return CType(Me("RightTrackerOBS"),String)
            End Get
            Set
                Me("RightTrackerOBS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CommentaryOBS() As String
            Get
                Return CType(Me("CommentaryOBS"),String)
            End Get
            Set
                Me("CommentaryOBS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property VLCMenuBar() As Boolean
            Get
                Return CType(Me("VLCMenuBar"),Boolean)
            End Get
            Set
                Me("VLCMenuBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property VLCPlayPauseControls() As Boolean
            Get
                Return CType(Me("VLCPlayPauseControls"),Boolean)
            End Get
            Set
                Me("VLCPlayPauseControls") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VLCStatusBar() As Boolean
            Get
                Return CType(Me("VLCStatusBar"),Boolean)
            End Get
            Set
                Me("VLCStatusBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VLCOverrideDefault() As Boolean
            Get
                Return CType(Me("VLCOverrideDefault"),Boolean)
            End Get
            Set
                Me("VLCOverrideDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HasFinishedWelcome() As Boolean
            Get
                Return CType(Me("HasFinishedWelcome"),Boolean)
            End Get
            Set
                Me("HasFinishedWelcome") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TwitchChannel() As String
            Get
                Return CType(Me("TwitchChannel"),String)
            End Get
            Set
                Me("TwitchChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DefaultConnection() As Boolean
            Get
                Return CType(Me("DefaultConnection"),Boolean)
            End Get
            Set
                Me("DefaultConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4444")>  _
        Public Property ConnectionPort1() As Integer
            Get
                Return CType(Me("ConnectionPort1"),Integer)
            End Get
            Set
                Me("ConnectionPort1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4443")>  _
        Public Property ConnectionPort2() As Integer
            Get
                Return CType(Me("ConnectionPort2"),Integer)
            End Get
            Set
                Me("ConnectionPort2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpgradeRequired() As Boolean
            Get
                Return CType(Me("UpgradeRequired"),Boolean)
            End Get
            Set
                Me("UpgradeRequired") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExpertMode() As Boolean
            Get
                Return CType(Me("ExpertMode"),Boolean)
            End Get
            Set
                Me("ExpertMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlwaysOnTop() As Boolean
            Get
                Return CType(Me("AlwaysOnTop"),Boolean)
            End Get
            Set
                Me("AlwaysOnTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("%LOCALAPPDATA%\Streamlink\bin\streamlink.exe")>  _
        Public Property StreamlinkPath() As String
            Get
                Return CType(Me("StreamlinkPath"),String)
            End Get
            Set
                Me("StreamlinkPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftStreamlinkVlcParams() As String
            Get
                Return CType(Me("LeftStreamlinkVlcParams"),String)
            End Get
            Set
                Me("LeftStreamlinkVlcParams") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightStreamlinkVlcParams() As String
            Get
                Return CType(Me("RightStreamlinkVlcParams"),String)
            End Get
            Set
                Me("RightStreamlinkVlcParams") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GameSettings() As String
            Get
                Return CType(Me("GameSettings"),String)
            End Get
            Set
                Me("GameSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("633")>  _
        Public Property DefaultHeight() As Integer
            Get
                Return CType(Me("DefaultHeight"),Integer)
            End Get
            Set
                Me("DefaultHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("863")>  _
        Public Property DefaultWidth() As Integer
            Get
                Return CType(Me("DefaultWidth"),Integer)
            End Get
            Set
                Me("DefaultWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("633")>  _
        Public Property FourRacerHeight() As Integer
            Get
                Return CType(Me("FourRacerHeight"),Integer)
            End Get
            Set
                Me("FourRacerHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1523")>  _
        Public Property FourRacerWidth() As Integer
            Get
                Return CType(Me("FourRacerWidth"),Integer)
            End Get
            Set
                Me("FourRacerWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("112")>  _
        Public Property DefaultGBHeight() As Integer
            Get
                Return CType(Me("DefaultGBHeight"),Integer)
            End Get
            Set
                Me("DefaultGBHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("658")>  _
        Public Property DefaultGBWidth() As Integer
            Get
                Return CType(Me("DefaultGBWidth"),Integer)
            End Get
            Set
                Me("DefaultGBWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("112")>  _
        Public Property FourRacerGBHeight() As Integer
            Get
                Return CType(Me("FourRacerGBHeight"),Integer)
            End Get
            Set
                Me("FourRacerGBHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1327")>  _
        Public Property FourRacerGBWidth() As Integer
            Get
                Return CType(Me("FourRacerGBWidth"),Integer)
            End Get
            Set
                Me("FourRacerGBWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FourPlayers() As Boolean
            Get
                Return CType(Me("FourPlayers"),Boolean)
            End Get
            Set
                Me("FourPlayers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftTimerName_Bottom() As String
            Get
                Return CType(Me("LeftTimerName_Bottom"),String)
            End Get
            Set
                Me("LeftTimerName_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftGameName_Bottom() As String
            Get
                Return CType(Me("LeftGameName_Bottom"),String)
            End Get
            Set
                Me("LeftGameName_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightGameName_Bottom() As String
            Get
                Return CType(Me("RightGameName_Bottom"),String)
            End Get
            Set
                Me("RightGameName_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightTimerName_Bottom() As String
            Get
                Return CType(Me("RightTimerName_Bottom"),String)
            End Get
            Set
                Me("RightTimerName_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftRunnerOBS_Bottom() As String
            Get
                Return CType(Me("LeftRunnerOBS_Bottom"),String)
            End Get
            Set
                Me("LeftRunnerOBS_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightRunnerOBS_Bottom() As String
            Get
                Return CType(Me("RightRunnerOBS_Bottom"),String)
            End Get
            Set
                Me("RightRunnerOBS_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftTrackerOBS_Bottom() As String
            Get
                Return CType(Me("LeftTrackerOBS_Bottom"),String)
            End Get
            Set
                Me("LeftTrackerOBS_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightTrackerOBS_Bottom() As String
            Get
                Return CType(Me("RightTrackerOBS_Bottom"),String)
            End Get
            Set
                Me("RightTrackerOBS_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LeftStreamlinkVlcParams_Bottom() As String
            Get
                Return CType(Me("LeftStreamlinkVlcParams_Bottom"),String)
            End Get
            Set
                Me("LeftStreamlinkVlcParams_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RightStreamlinkVlcParams_Bottom() As String
            Get
                Return CType(Me("RightStreamlinkVlcParams_Bottom"),String)
            End Get
            Set
                Me("RightStreamlinkVlcParams_Bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("558")>  _
        Public Property BoundingSizeWidthGameTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthGameTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthGameTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("446")>  _
        Public Property BoundingSizeHeightGameTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightGameTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightGameTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("178")>  _
        Public Property BoundingSizeWidthTimerTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthTimerTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthTimerTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("47")>  _
        Public Property BoundingSizeHeightTimerTwoPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightTimerTwoPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightTimerTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("383")>  _
        Public Property BoundingSizeWidthGameFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthGameFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthGameFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property BoundingSizeHeightGameFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightGameFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightGameFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("119")>  _
        Public Property BoundingSizeWidthTimerFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeWidthTimerFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeWidthTimerFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property BoundingSizeHeightTimerFourPlayer() As Integer
            Get
                Return CType(Me("BoundingSizeHeightTimerFourPlayer"),Integer)
            End Get
            Set
                Me("BoundingSizeHeightTimerFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1116")>  _
        Public Property PositionXTimerTopRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionXTimerTopRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXTimerTopRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("51")>  _
        Public Property PositionYTimerTopRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionYTimerTopRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYTimerTopRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1116")>  _
        Public Property PositionXTimerBottomRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionXTimerBottomRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXTimerBottomRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("410")>  _
        Public Property PositionYTimerBottomRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionYTimerBottomRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYTimerBottomRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property PositionXTimerTopLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionXTimerTopLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXTimerTopLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("52")>  _
        Public Property PositionYTimerTopLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionYTimerTopLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYTimerTopLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property PositionXTimerBottomLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionXTimerBottomLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXTimerBottomLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("410")>  _
        Public Property PositionYTimerBottomLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionYTimerBottomLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYTimerBottomLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("676")>  _
        Public Property PositionXGameTopRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionXGameTopRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXGameTopRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property PositionYGameTopRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionYGameTopRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYGameTopRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("676")>  _
        Public Property PositionXGameBottomRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionXGameBottomRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXGameBottomRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("368")>  _
        Public Property PositionYGameBottomRightFourPlayer() As Integer
            Get
                Return CType(Me("PositionYGameBottomRightFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYGameBottomRightFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("220")>  _
        Public Property PositionXGameTopLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionXGameTopLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXGameTopLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property PositionYGameTopLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionYGameTopLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYGameTopLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("220")>  _
        Public Property PositionXGameBottomLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionXGameBottomLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionXGameBottomLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("368")>  _
        Public Property PositionYGameBottomLeftFourPlayer() As Integer
            Get
                Return CType(Me("PositionYGameBottomLeftFourPlayer"),Integer)
            End Get
            Set
                Me("PositionYGameBottomLeftFourPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1046")>  _
        Public Property PositionXTimerRightTwoPlayer() As Integer
            Get
                Return CType(Me("PositionXTimerRightTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionXTimerRightTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property PositionYTimerRightTwoPlayer() As Integer
            Get
                Return CType(Me("PositionYTimerRightTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionYTimerRightTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("56")>  _
        Public Property PositionXTimerLeftTwoPlayer() As Integer
            Get
                Return CType(Me("PositionXTimerLeftTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionXTimerLeftTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property PositionYTimerLeftTwoPlayer() As Integer
            Get
                Return CType(Me("PositionYTimerLeftTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionYTimerLeftTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("674")>  _
        Public Property PositionXGameRightTwoPlayer() As Integer
            Get
                Return CType(Me("PositionXGameRightTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionXGameRightTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("83")>  _
        Public Property PositionYGameRightTwoPlayer() As Integer
            Get
                Return CType(Me("PositionYGameRightTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionYGameRightTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("48")>  _
        Public Property PositionXGameLeftTwoPlayer() As Integer
            Get
                Return CType(Me("PositionXGameLeftTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionXGameLeftTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("83")>  _
        Public Property PositionYGameLeftTwoPlayer() As Integer
            Get
                Return CType(Me("PositionYGameLeftTwoPlayer"),Integer)
            End Get
            Set
                Me("PositionYGameLeftTwoPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SelectedConfigName() As String
            Get
                Return CType(Me("SelectedConfigName"),String)
            End Get
            Set
                Me("SelectedConfigName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SelectedConfigPath() As String
            Get
                Return CType(Me("SelectedConfigPath"),String)
            End Get
            Set
                Me("SelectedConfigPath") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ALTTPRCropDashboard.My.MySettings
            Get
                Return Global.ALTTPRCropDashboard.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
